import 'dart:convert';
import 'dart:io';
import 'package:archive/archive.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';

class DocumentExportService extends GetxService {
  static DocumentExportService get to => Get.find<DocumentExportService>();

  /// Export markdown text content to a professional PDF file
  Future<File?> exportPdf({
    required String title,
    required String markdownContent,
    bool openShare = true,
  }) async {
    try {
      final document = PdfDocument();
      document.pageSettings.margins.all = 36; // 0.5 inch margins

      // Palette
      final titleFont = PdfStandardFont(PdfFontFamily.helvetica, 20, style: PdfFontStyle.bold);
      final h1Font = PdfStandardFont(PdfFontFamily.helvetica, 15, style: PdfFontStyle.bold);
      final h2Font = PdfStandardFont(PdfFontFamily.helvetica, 13, style: PdfFontStyle.bold);
      final bodyFont = PdfStandardFont(PdfFontFamily.helvetica, 10.5);
      final codeFont = PdfStandardFont(PdfFontFamily.courier, 9.5);
      final captionFont = PdfStandardFont(PdfFontFamily.helvetica, 8.5, style: PdfFontStyle.italic);

      final textColor = PdfColor(18, 20, 29);
      final mutedColor = PdfColor(100, 105, 120);
      final accentColor = PdfColor(20, 22, 32);

      // Extract lines
      final lines = markdownContent.split('\n');
      final cleanTitle = title.trim().isEmpty ? 'Document' : title.trim();

      // Layout elements sequentially
      PdfPage page = document.pages.add();
      double yOffset = 0;
      final pageWidth = page.getClientSize().width;
      final pageHeight = page.getClientSize().height;

      // Header Banner
      final headerText = cleanTitle;
      page.graphics.drawString(
        headerText,
        titleFont,
        brush: PdfSolidBrush(accentColor),
        bounds: Rect.fromLTWH(0, yOffset, pageWidth, 28),
      );
      yOffset += 30;

      final dateStr = DateFormat('MMMM d, yyyy · HH:mm').format(DateTime.now());
      page.graphics.drawString(
        'Generated by AstraLM · $dateStr',
        captionFont,
        brush: PdfSolidBrush(mutedColor),
        bounds: Rect.fromLTWH(0, yOffset, pageWidth, 16),
      );
      yOffset += 20;

      // Divider line
      page.graphics.drawLine(
        PdfPen(PdfColor(220, 224, 235), width: 1),
        Offset(0, yOffset),
        Offset(pageWidth, yOffset),
      );
      yOffset += 14;

      bool inCodeBlock = false;
      final codeBlockBuffer = StringBuffer();

      for (int i = 0; i < lines.length; i++) {
        final line = lines[i];

        // Code block start/end
        if (line.trim().startsWith('```')) {
          if (inCodeBlock) {
            // Draw code block
            final codeText = codeBlockBuffer.toString();
            codeBlockBuffer.clear();
            inCodeBlock = false;

            final codeElement = PdfTextElement(
              text: codeText,
              font: codeFont,
              brush: PdfSolidBrush(textColor),
            );

            final layoutResult = codeElement.draw(
              page: page,
              bounds: Rect.fromLTWH(0, yOffset, pageWidth, pageHeight - yOffset),
            );

            if (layoutResult != null) {
              page = layoutResult.page;
              yOffset = layoutResult.bounds.bottom + 10;
            }
          } else {
            inCodeBlock = true;
            yOffset += 6;
          }
          continue;
        }

        if (inCodeBlock) {
          codeBlockBuffer.writeln(line);
          continue;
        }

        final trimmed = line.trim();
        if (trimmed.isEmpty) {
          yOffset += 8;
          continue;
        }

        // Check if heading
        PdfFont currentFont = bodyFont;
        PdfColor currentTextColor = textColor;
        String textToDraw = trimmed;
        double spacingAfter = 6;

        if (trimmed.startsWith('# ')) {
          currentFont = h1Font;
          textToDraw = trimmed.substring(2).trim();
          spacingAfter = 10;
          yOffset += 6;
        } else if (trimmed.startsWith('## ')) {
          currentFont = h2Font;
          textToDraw = trimmed.substring(3).trim();
          spacingAfter = 8;
          yOffset += 4;
        } else if (trimmed.startsWith('### ')) {
          currentFont = h2Font;
          textToDraw = trimmed.substring(4).trim();
          spacingAfter = 6;
          yOffset += 2;
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          textToDraw = '•  ${trimmed.substring(2).trim()}';
        } else if (RegExp(r'^\d+\.\s').hasMatch(trimmed)) {
          textToDraw = trimmed;
        }

        // Strip inline markdown bold/italic asterisks for clean PDF output
        textToDraw = textToDraw.replaceAll('**', '').replaceAll('*', '').replaceAll('`', '');

        final textElement = PdfTextElement(
          text: textToDraw,
          font: currentFont,
          brush: PdfSolidBrush(currentTextColor),
          format: PdfStringFormat(lineSpacing: 2),
        );

        final result = textElement.draw(
          page: page,
          bounds: Rect.fromLTWH(0, yOffset, pageWidth, pageHeight - yOffset),
        );

        if (result != null) {
          page = result.page;
          yOffset = result.bounds.bottom + spacingAfter;
        }
      }

      // If open code block remains
      if (inCodeBlock && codeBlockBuffer.isNotEmpty) {
        final codeElement = PdfTextElement(
          text: codeBlockBuffer.toString(),
          font: codeFont,
          brush: PdfSolidBrush(textColor),
        );
        final result = codeElement.draw(
          page: page,
          bounds: Rect.fromLTWH(0, yOffset, pageWidth, pageHeight - yOffset),
        );
        if (result != null) {
          page = result.page;
          yOffset = result.bounds.bottom + 8;
        }
      }

      // Add page numbers footer
      for (int p = 0; p < document.pages.count; p++) {
        final pPage = document.pages[p];
        final footerStr = 'Page ${p + 1} of ${document.pages.count}';
        pPage.graphics.drawString(
          footerStr,
          captionFont,
          brush: PdfSolidBrush(mutedColor),
          bounds: Rect.fromLTWH(0, pPage.getClientSize().height - 14, pPage.getClientSize().width, 14),
          format: PdfStringFormat(alignment: PdfTextAlignment.right),
        );
      }

      final bytes = await document.save();
      document.dispose();

      // Save file
      final fileName = '${_slugify(cleanTitle)}_${DateTime.now().millisecondsSinceEpoch}.pdf';
      final file = await _saveBytesToFile(bytes, fileName);

      if (openShare && file != null) {
        await Share.shareXFiles(
          [XFile(file.path, mimeType: 'application/pdf', name: fileName)],
          text: 'Sharing $cleanTitle (PDF)',
        );
      }

      Get.snackbar(
        'PDF Exported',
        'Saved as $fileName',
        snackPosition: SnackPosition.TOP,
        duration: const Duration(seconds: 3),
        backgroundColor: const Color(0xFF141620),
        colorText: Colors.white,
        icon: const Icon(Icons.picture_as_pdf_rounded, color: Colors.white),
        margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        borderRadius: 16,
      );

      return file;
    } catch (e) {
      Get.snackbar(
        'Export Failed',
        'Could not generate PDF: $e',
        snackPosition: SnackPosition.TOP,
        backgroundColor: const Color(0xFF3B1A1A),
        colorText: Colors.white,
      );
      return null;
    }
  }

  /// Export markdown text content to a Microsoft Word Document (.docx)
  Future<File?> exportDocx({
    required String title,
    required String markdownContent,
    bool openShare = true,
  }) async {
    try {
      final cleanTitle = title.trim().isEmpty ? 'Document' : title.trim();
      final dateStr = DateFormat('MMMM d, yyyy · HH:mm').format(DateTime.now());

      final lines = markdownContent.split('\n');
      final bodyXmlBuffer = StringBuffer();

      // Title
      bodyXmlBuffer.write('''
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Title"/>
        <w:spacing w:before="240" w:after="120"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:rFonts w:ascii="Helvetica" w:hAnsi="Helvetica"/>
          <w:b/>
          <w:sz w:val="48"/>
          <w:color w:val="12141D"/>
        </w:rPr>
        <w:t>${_escapeXml(cleanTitle)}</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:spacing w:before="0" w:after="240"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:rFonts w:ascii="Helvetica" w:hAnsi="Helvetica"/>
          <w:i/>
          <w:sz w:val="18"/>
          <w:color w:val="6B7284"/>
        </w:rPr>
        <w:t>Generated by AstraLM · ${_escapeXml(dateStr)}</w:t>
      </w:r>
    </w:p>
''');

      bool inCodeBlock = false;
      final codeBuffer = StringBuffer();

      for (final line in lines) {
        if (line.trim().startsWith('```')) {
          if (inCodeBlock) {
            // Write code block paragraph
            final codeText = codeBuffer.toString();
            codeBuffer.clear();
            inCodeBlock = false;

            bodyXmlBuffer.write('''
    <w:p>
      <w:pPr>
        <w:pBdr>
          <w:left w:val="single" w:sz="12" w:space="4" w:color="33384C"/>
        </w:pBdr>
        <w:shd w:val="clear" w:color="auto" w:fill="F3F5F9"/>
        <w:spacing w:before="120" w:after="120" w:line="240" w:lineRule="auto"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:rFonts w:ascii="Consolas" w:hAnsi="Consolas"/>
          <w:sz w:val="19"/>
          <w:color w:val="1A1E2B"/>
        </w:rPr>
        <w:t xml:space="preserve">${_escapeXml(codeText)}</w:t>
      </w:r>
    </w:p>
''');
          } else {
            inCodeBlock = true;
          }
          continue;
        }

        if (inCodeBlock) {
          codeBuffer.writeln(line);
          continue;
        }

        final trimmed = line.trim();
        if (trimmed.isEmpty) {
          bodyXmlBuffer.write('''<w:p><w:pPr><w:spacing w:after="100"/></w:pPr></w:p>''');
          continue;
        }

        if (trimmed.startsWith('# ')) {
          bodyXmlBuffer.write('''
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Heading1"/>
        <w:spacing w:before="240" w:after="100"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:rFonts w:ascii="Helvetica" w:hAnsi="Helvetica"/>
          <w:b/>
          <w:sz w:val="32"/>
          <w:color w:val="141620"/>
        </w:rPr>
        <w:t>${_escapeXml(trimmed.substring(2).trim())}</w:t>
      </w:r>
    </w:p>
''');
        } else if (trimmed.startsWith('## ')) {
          bodyXmlBuffer.write('''
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Heading2"/>
        <w:spacing w:before="180" w:after="80"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:rFonts w:ascii="Helvetica" w:hAnsi="Helvetica"/>
          <w:b/>
          <w:sz w:val="26"/>
          <w:color w:val="222634"/>
        </w:rPr>
        <w:t>${_escapeXml(trimmed.substring(3).trim())}</w:t>
      </w:r>
    </w:p>
''');
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          bodyXmlBuffer.write('''
    <w:p>
      <w:pPr>
        <w:pStyle w:val="ListParagraph"/>
        <w:spacing w:before="40" w:after="40"/>
        <w:ind w:left="400"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:rFonts w:ascii="Helvetica" w:hAnsi="Helvetica"/>
          <w:sz w:val="21"/>
          <w:color w:val="1A1D27"/>
        </w:rPr>
        <w:t>•  ${_escapeXml(trimmed.substring(2).trim())}</w:t>
      </w:r>
    </w:p>
''');
        } else {
          final cleanText = trimmed.replaceAll('**', '').replaceAll('*', '').replaceAll('`', '');
          bodyXmlBuffer.write('''
    <w:p>
      <w:pPr>
        <w:spacing w:before="40" w:after="80" w:line="280" w:lineRule="auto"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:rFonts w:ascii="Helvetica" w:hAnsi="Helvetica"/>
          <w:sz w:val="22"/>
          <w:color w:val="1E2230"/>
        </w:rPr>
        <w:t>${_escapeXml(cleanText)}</w:t>
      </w:r>
    </w:p>
''');
        }
      }

      final docXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:body>
${bodyXmlBuffer.toString()}
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>
    </w:sectPr>
  </w:body>
</w:document>''';

      final contentTypesXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>''';

      final relsXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>''';

      // Zip package
      final archive = Archive()
        ..addFile(ArchiveFile('[Content_Types].xml', contentTypesXml.length, utf8.encode(contentTypesXml)))
        ..addFile(ArchiveFile('_rels/.rels', relsXml.length, utf8.encode(relsXml)))
        ..addFile(ArchiveFile('word/document.xml', docXml.length, utf8.encode(docXml)));

      final zipData = ZipEncoder().encode(archive);
      if (zipData == null) throw Exception('Failed to encode .docx zip archive');

      final fileName = '${_slugify(cleanTitle)}_${DateTime.now().millisecondsSinceEpoch}.docx';
      final file = await _saveBytesToFile(zipData, fileName);

      if (openShare && file != null) {
        await Share.shareXFiles(
          [XFile(file.path, mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', name: fileName)],
          text: 'Sharing $cleanTitle (Word DOCX)',
        );
      }

      Get.snackbar(
        'Word Doc Exported',
        'Saved as $fileName',
        snackPosition: SnackPosition.TOP,
        duration: const Duration(seconds: 3),
        backgroundColor: const Color(0xFF141620),
        colorText: Colors.white,
        icon: const Icon(Icons.description_rounded, color: Colors.white),
        margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        borderRadius: 16,
      );

      return file;
    } catch (e) {
      Get.snackbar(
        'Export Failed',
        'Could not generate DOCX: $e',
        snackPosition: SnackPosition.TOP,
        backgroundColor: const Color(0xFF3B1A1A),
        colorText: Colors.white,
      );
      return null;
    }
  }

  Future<File?> _saveBytesToFile(List<int> bytes, String fileName) async {
    try {
      Directory? dir;
      if (Platform.isAndroid) {
        final downloadDir = Directory('/storage/emulated/0/Download');
        if (await downloadDir.exists()) {
          dir = downloadDir;
        }
      }
      dir ??= await getApplicationDocumentsDirectory();

      final file = File('${dir.path}/$fileName');
      await file.writeAsBytes(bytes, flush: true);
      return file;
    } catch (e) {
      final fallbackDir = await getApplicationDocumentsDirectory();
      final file = File('${fallbackDir.path}/$fileName');
      await file.writeAsBytes(bytes, flush: true);
      return file;
    }
  }

  String _slugify(String text) {
    return text
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
        .replaceAll(RegExp(r'^_+|_+$'), '');
  }

  String _escapeXml(String text) {
    return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
  }
}
